from __future__ import annotations

SUBAGENT_INPUT_INVALID = "SUBAGENT_INPUT_INVALID"

EXECUTOR_REPEATED_CALL = "EXECUTOR_REPEATED_CALL"
EXECUTOR_MAX_CALLS = "EXECUTOR_MAX_CALLS"
EXECUTOR_TOKEN_BUDGET_EXCEEDED = "EXECUTOR_TOKEN_BUDGET_EXCEEDED"
EXECUTOR_TIMEOUT = "EXECUTOR_TIMEOUT"
EXECUTOR_LLM_RAISED = "EXECUTOR_LLM_RAISED"
EXECUTOR_LLM_STALLED = "EXECUTOR_LLM_STALLED"
EXECUTOR_DID_NOT_FINALIZE = "EXECUTOR_DID_NOT_FINALIZE"
EXECUTOR_MILESTONE_NOT_DONE = "EXECUTOR_MILESTONE_NOT_DONE"

FINDER_FETCH_FAILED = "FINDER_FETCH_FAILED"

PLANNER_LLM_RAISED = "PLANNER_LLM_RAISED"

# Unified 429 label: the configured provider backoff ladder was fully consumed.
# Provider quota problem, NOT an agent failure — the controller aborts the
# run immediately (no continuation revise / repair prompt, no trajectory
# pollution) and the task is rerun after the batch, like TIMED_OUT.
PROVIDER_RATE_LIMITED = "PROVIDER_RATE_LIMITED"

__all__ = [
    "SUBAGENT_INPUT_INVALID",
    "EXECUTOR_REPEATED_CALL",
    "EXECUTOR_MAX_CALLS",
    "EXECUTOR_TOKEN_BUDGET_EXCEEDED",
    "EXECUTOR_TIMEOUT",
    "EXECUTOR_LLM_RAISED",
    "EXECUTOR_LLM_STALLED",
    "EXECUTOR_DID_NOT_FINALIZE",
    "EXECUTOR_MILESTONE_NOT_DONE",
    "FINDER_FETCH_FAILED",
    "PLANNER_LLM_RAISED",
    "PROVIDER_RATE_LIMITED",
]
